({
	"ConfirmPassword": "Confirm Password",
	"CurrentWindow": "Current Window",
	"DatabaseErrorCheckInstall": "A database error occured. Check Lucid Desktop is installed correctly or contact the Administrator.",
	"DesktopLogin": "Lucid Desktop Login",
	"Email": "Email",
	"EmailUserMismatch": "Email on file and username don't match",
	"EnterValidEmail": "Please enter a valid email",
	"FillAllFields": "Please fill in all fields",
	"IncorrectUserPass": "Incorrect username or password.",
	"LoggedInClick": "You are already logged in. <a href='" + dojo.baseUrl + "../../index.html'>Click here</a> to continue to the desktop.",
	"LoggedInClickToOpen": "You are already logged in. <a href='" + dojo.baseUrl + "../../index.html'>Click here</a> to open the desktop.",
	"LoggedInRedirect": "You are already logged in. Redirecting to desktop...",
	"LoggedInRedirecting": "Logged in. Redirecting to desktop...",
	"LoggedInWindowOpened": "You are already logged in. Window opened.",
	"LoggingIn": "Logging in...",
	"Login": "Login",
	"MayLog": "You may now log in",
	"NewPassSent": "A new password has been sent",
	"NewWindow": "New window",
	"NoPermissionLogin": "You do not have permission to login. Contact the Administrator.",
	"NoSuchUser": "No such user",
	"PassMismatch": "Two passwords don't match",
	"Password": "Password",
	"PopupBlockerBlockingDesktop": "Your popup blocker is blocking the Lucid Desktop window.",
	"PopupBlocker": "Your popup blocker is blocking the window. <a href='" + dojo.baseUrl + "../../index.html'>Click here</a> to try again.",
	"ProvideUserPass": "Please provide both a username and a password",
	"PublicRegisterDisabled": "Public registations are disabled",
	"Register": "Register",
	"ResetPassword": "Reset Password",
	"Submit": "Submit",
	"UnknownError": "Unknown Error occured. Check your installation.",
	"Username": "Username",
	"UsernameExists": "Username already exists",
	"UsernameNo2Dots": "Username cannot contain two consecutive '.'s",
	"UsernameNoSlashes": "Username cannot contain any slashes",
	"RememberMe":"Remember Me"
})
