({
	"ConfirmPassword": "Confirmer votre mot de passe",
	"CurrentWindow": "Fenêtre actuelle",
	"DatabaseErrorCheckInstall": "Une erreur a eu lieu. Svp, veuillez vérifier l'installation de Lucid Desktop ou contactez votre administrateur.",
	"DesktopLogin": "Connexion",
	"Email": "Courriel",
	"EmailUserMismatch": "Le courriel enregistré et le nom d'utilisateur ne correspondent pas",
	"EnterValidEmail": "Svp, veuillez saisir une adresse de courriel valide",
	"FillAllFields": "Svp, veuillez saisir tous les champs",
	"IncorrectUserPass": "Nom d'utilisateur ou mot de passe incorrect.",
	"LoggedInClick": "Vous êtes déjà connecté. <a href='" + dojo.baseUrl + "../../index.html'>Cliquez ici</a> pour continuer.",
	"LoggedInClickToOpen": "Vous êtes déjà connecté. <a href='" + dojo.baseUrl + "../../index.html'>Cliquez ici</a> pour ouvrir le bureau.",
	"LoggedInRedirect": "Vous êtes déjà connecté. Redirection vers le bureau...",
	"LoggedInRedirecting": "Connecté. Redirection vers le bureau...",
	"LoggedInWindowOpened": "Vous êtes déjà connecté. Fenêtre ouverte.",
	"LoggingIn": "Connexion en cours...",
	"Login": "Connexion",
	"MayLog": "Vous pouvez maintenant vous connecter",
	"NewPassSent": "Un nouveau mot de passe vous a été transmis.",
	"NewWindow": "Nouvelle fenêtre",
	"NoPermissionLogin": "Vous n'avez pas la permission de vous connecter. Veuillez communiquer avec l'administrateur.",
	"NoSuchUser": "Utilisateur inconnu",
	"PassMismatch": "Les deux mots de passe ne correspondent pas",
	"Password": "Mot de passe",
	"PopupBlockerBlockingDesktop": "Votre bloqueur de fenêtre empêche l'affichage de la fenêtre de Lucid Desktop.",
	"PopupBlocker": "Votre bloqueur de fenêtre empêche l'affichage de la fenêtre. <a href='" + dojo.baseUrl + "../../index.html'>Cliquer ici</a> pour réessayer.",
	"ProvideUserPass": "Svp, veuillez saisir votre nom d'utilisateur et votre mot de passe",
	"PublicRegisterDisabled": "Les enregistrements publiques sont désactivés",
	"Register": "Enregistrement",
	"ResetPassword": "Réinitialiser le mot de passe",
	"Submit": "Envoyer",
	"UnknownError": "Une erreur inconnue a eu lieu. Svp, veuillez vérifier votre installatin.",
	"Username": "Nom d'utilisateur",
	"UsernameExists": "Ce nom d'utilisateur existe déjà",
	"UsernameNo2Dots": "Un nom d'utlisateur ne peut contenir deux '.' consécutifs",
	"UsernameNoSlashes": "Un nom d'utilisateur ne peut contenir de barre oblique",
	"RememberMe":"Se souvenir de moi"
})
