define("openstar/nls/ja/system", 
({
"initial":"Allow by default",
"createNewGroup":"Create new group",
"installAppPackage":"Install app package",
"killFail":"Instance %s was NOT killed sucessfully.",
"themeInstallSuccess":"Theme package installation successful!",
"version":"Version",
"installThemeInstructions":"Select a theme package to install from your local hard disk",
"appInstallSuccess":"App package installation successful!",
"active":"Active",
"chUsersPassword":"Change %s's password",
"filetypes":"Filetypes",
"installThemePackage":"Install theme package",
"launchingApp":"Starting %s...",
"instance":"Instance",
"allow":"Allow",
"themeDelConfirm":"Theme deletion confirmation",
"unlimited":"Unlimited",
"actions":"Actions",
"modifyQuotaGeneric":"Modify quota",
"permsFor":"Permissions for %s",
"logged":"Logged In",
"killSuccess":"Instance %s was killed sucessfully.",
"id":"ID",
"zombie":"Zombie",
"allreadyKilled":"This process has already been killed or has exited.",
"lastauth":"Last Authentication",
"status":"Status",
"appDelConfirm":"App deletion confirmation",
"sysname":"System Name",
"createNewUser":"Create new user",
"preview":"Preivew",
"userDelConfirm":"User deletion confirmation",
"email":"Email",
"manageGroupMembers":"Manage %s members",
"compatible":"Compatibility",
"diskUsage":"Disk Usage",
"kill":"Kill",
"alterPermissions":"Alter Permissions",
"quota":"Quota",
"notCompatible":"Package incompatible",
"groupAlreadyExists":"Group with that name already exists",
"modifyQuota":"Modify %s's quota",
"delFromSys":"Are you sure you want to permanently delete %s from the system?",
"killed":"Killed",
"description":"Description",
"name":"Name",
"permissions":"Permissions",
"default":"Default",
"manageGroupMembersGeneric":"Manage group members",
"groupDelConfirm":"Group deletion confirmation",
"installAppInstructions":"Select an app package to install from your local hard disk",
"groups":"Groups",
"home":"Home",
"author":"Author",
"category":"Category",
"deny":"Deny",
"notCompatibleText":"The package you have installed may be incompatible with this version of Lucid. Please check the provider's site for an up-to-date version.",
"maturity":"Maturity",
"apps":"Apps",
"usersOnline":"Users online",
"users":"Users",
"themes":"Themes",
"notAssigned":"Not yet assigned"
})
);