define({ root:
({
"name":"Name",
"confirmNewPassword":"Retype new password",
"passwordDirections":"To change your password, enter your current password in the field below and click <b>Authenticate</b>.<br />After you have authenticated, enter your new password, retype it for verification and click <b>Change Password</b>",
"unknown":"(Unknown)",
"vendor":"Vendor",
"accountInfo":"Account Information",
"authFail":"Authentication failed",
"changePasswordAction":"Change Password...",
"authSuccess":"Authentication was successful",
"changePassword":"Change password",
"action":"Action",
"attemptsRemaining":"Attempt(s) remaining",
"newPassword":"New password",
"authenticate":"Authenticate",
"language":"Language",
"cannotContain":"Username cannot contain \"%s\"",
"email":"Email",
"currentPassword":"Current password",
"sudoExplination":"An application is attempting to perform an action which requires privileges. Authentication is required to perform this action.",
"changingPassword":"Changing password...",
"passwordsDontMatch":"The two passwords do not match",
"usernameAllreadyTaken":"Username already taken",
"general":"General",
"passwordsMatch":"The two passwords match",
"program":"Program",
"restartDesktopForLangChange":"You must restart the desktop for the language change to occur",
"confirmPassword":"Confirm password",
"enterUsername":"Enter a username",
"userCreated":"User created",
"username":"Username",
"passwordChangeSuccessful":"Password change successful",
"enterPassword":"Enter a password",
"password":"Password",
"enterValidEmail":"Enter a valid email",
"authRequired":"Authentication required"
})
,
"ja": true
});
